include basic usage instructions
ericaltendorf/plotman pull request #204
Opened 2021-05-01 11:11 UTC by drewmullen

include note on issue when installing plotman on rhel via chia's guide

include basic usage steps

2021-05-07 04:00 UTC, altendky requested changes
Thanks for the follow up here.  Sorry for the wait on the review.

2021-05-07 04:00 UTC, altendky commented on README.md
> +3. Configure (default location ~/.config/plotman/plotman.yaml). Options explained in the default config file (step 2)
This location is OS specific.  `plotman config path` will tell you the actual path that will be looked for.

2021-05-07 04:00 UTC, altendky commented on README.md
> +5. `plotman plot`
Do we want to encourage `plot` or `interactive`?  I'm not really sure...

2021-05-07 05:07 UTC, ericaltendorf commented
regarding `plot` vs `interactive`, I think we can suggest both, each with a
one-liner saying what it does.  i wonder if some people are using `plot`
just to avoid the archiving that `interactive` does by default?

On Thu, May 6, 2021 at 9:00 PM Kyle Altendorf ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for the follow up here. Sorry for the wait on the review.
> ------------------------------
>
> In README.md
> <https://github.com/ericaltendorf/plotman/pull/204#discussion_r627907354>:
>
> > @@ -200,6 +200,20 @@ Installation for Linux:
>  4. That's it! You can now run Plotman by typing `plotman version` to verify its version.
>     Run `plotman --help` to learn about the available commands.
>
> +*Note:* If you see `ModuleNotFoundError: No module named 'readline'` when using `plotman` on [RHEL based linux](https://github.com/ericaltendorf/plotman/issues/195) after installing using [chia's guide](https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#centos--red-hat--fedora), install `readline-devel` then reinstall chia starting at compiling python in a new build environment; or consider using a project like `pyenv`.
> +
> +## Basic Usage:
> +
> +1. Install
> +
> +2. Generate initial config
> +
> +3. Configure (default location ~/.config/plotman/plotman.yaml). Options explained in the default config file (step 2)
>
> This location is OS specific. plotman config path will tell you the
> actual path that will be looked for.
> ------------------------------
>
> In README.md
> <https://github.com/ericaltendorf/plotman/pull/204#discussion_r627907530>:
>
> > @@ -200,6 +200,20 @@ Installation for Linux:
>  4. That's it! You can now run Plotman by typing `plotman version` to verify its version.
>     Run `plotman --help` to learn about the available commands.
>
> +*Note:* If you see `ModuleNotFoundError: No module named 'readline'` when using `plotman` on [RHEL based linux](https://github.com/ericaltendorf/plotman/issues/195) after installing using [chia's guide](https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#centos--red-hat--fedora), install `readline-devel` then reinstall chia starting at compiling python in a new build environment; or consider using a project like `pyenv`.
> +
> +## Basic Usage:
> +
> +1. Install
> +
> +2. Generate initial config
> +
> +3. Configure (default location ~/.config/plotman/plotman.yaml). Options explained in the default config file (step 2)
> +
> +4. Create log directory specified in `directories: { log: "" }`
> +
> +5. `plotman plot`
>
> Do we want to encourage plot or interactive? I'm not really sure...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ericaltendorf/plotman/pull/204#pullrequestreview-654060246>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARPZIFUTMHIZCKMIIIPYSY3TMNQWDANCNFSM436HCMYQ>
> .
>

2021-05-15 20:47 UTC, altendky approved these changes
Ugh, I need to start processing from the end of the PR least, not the beginning...  to avoid leaving PRs like this languishing.  My apologies.

I'm going to call this good.  If you want to add more, feel free to follow up with another PR.  Hopefully I find dev time soon so we can get away from tmux being useful but for now people seem to like it (along with screen).

2021-05-15 20:51 UTC, merged