allow empty dst directory, if so, the tmp directory is used as buffer.
ericaltendorf/plotman pull request #234
Opened 2021-05-04 12:58 UTC by wisherhxl

set dst directory to optional, if directory.dst is None, no buffer will be used, chia plot command will set dst directory to tmp directory.
If multiple fast M.2(>3000M/s) ssd is used and not raid, archive directly from the tmp directory can save disk and time.

2021-05-07 03:38 UTC, altendky requested changes
Thanks for the work here, it looks like a good addition.  It half applies to me right now (the dst-on-tmp part) and maybe fully next week depending if I RAID in my new system or not (the multiple tmp drives part).  If you could test it out for a bit to make sure it works, that would be great.

2021-05-07 03:38 UTC, altendky commented on src/plotman/configuration.py
> +        (True, dir_cfg.dst)
What do you think of making this a method or two on `Directories`?  Maybe `dir_cfg.dst_is_tmp()` and `dir_cfg.effective_dst_dirs()` or such?

Also, as is, this is missing returns for the specified tuples.

2021-05-09 03:31 UTC, wisherhxl commented
> Thanks for the work here, it looks like a good addition. It half applies to me right now (the dst-on-tmp part) and maybe fully next week depending if I RAID in my new system or not (the multiple tmp drives part). If you could test it out for a bit to make sure it works, that would be great.

I'm using multiple M.2 SSD and use them seperately, so you will be fine. using tmp dir as dst can save the copy time, but not recommand for HDDs.

2021-05-14 14:34 UTC, altendky commented
I don't know if we just lost each other or what, but I hope you don't mind that I'm going to catch this up and finish it out.  Thanks so much for the contribution.  I look forward to being able to use this whenever I finally get my new setup...  `:]`

2021-05-15 20:55 UTC, altendky approved these changes
I've been running this for a day or two without issue.  Excited to get another temp setup so I need this.  `:]`  Thanks again for the work here @wisherhxl.

2021-05-15 20:55 UTC, merged

2021-05-21 00:16 UTC, 7AC commented
Is there an ETA for a release with this?

2021-05-21 00:21 UTC, altendky commented
Maybe a week?  Other than trying to kind of not really keep up with reported issues etc, I have a custom archiving change that I'd like to get out.  You can use the regular installation instructions and replace `@main` with `@development` to use it now.

2021-05-21 00:22 UTC, 7AC commented
Thanks appreciate it.

> On May 20, 2021, at 5:21 PM, Kyle Altendorf ***@***.***> wrote:
> 
> 
> Maybe a week? Other than trying to kind of not really keep up with reported issues etc, I have a custom archiving change that I'd like to get out. You can use the regular installation instructions and replace @main with @development to use it now.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/ericaltendorf/plotman/pull/234#issuecomment-845566121>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAFTLQ7DKW7VF6FO5QCRC63TOWRQHANCNFSM44CVFRZQ>.
>