adds logs printing command
ericaltendorf/plotman pull request #509
Opened 2021-05-17 03:15 UTC by mruckli

Introduces a logs command inspired by how `docker logs` works when interacting with containers but now for plots via plotman.
Basically I got sick of running `plotman status` then `plotman details` and afterwards `tail` or `less` for the given logfile. Now it is possible to simply print or follow the logs after getting the id of the plot via `plotman status`.

2021-06-14 01:23 UTC, altendky commented
I apologize for not keeping up with the community contributions.  This does look like a nice, concise, and useful addition.  Do you have time to catch it up with the changes to the `development` branch?  If so I can take a look and hopefully get it merged soon.

2021-06-18 21:49 UTC, mruckli commented
No worries, I understand that it must be hectic with so many things to work on :)
I updated it to the latest development branch.

2021-06-19 01:25 UTC, altendky requested changes

2021-06-19 01:25 UTC, altendky commented on src/plotman/job.py
> +    def print_logs(self, follow=None):
I think this might be enough to satisfy the type hints checking.

```suggestion
    def print_logs(self, follow: bool = False) -> None:
```

2021-06-21 01:33 UTC, altendky commented
I hope you don't mind me butting in and finishing out the remaining boilerplate.  Thanks for your contribution here.  `:]`

2021-06-21 01:33 UTC, merged