Clean up curses interface rendering
ericaltendorf/plotman pull request #72
Opened 2021-04-02 18:02 UTC by ericaltendorf

Main functional change: switch from `stdscr.getmaxyx()` to `os.popen('stty size', 'r')`, since the former doesn't seem to work (at least on my system).  Possibly a bug in curses, or a bad compile-time setting for the python curses library.  Some background: https://stackoverflow.com/questions/33906183#33906270

Allow "window" (curses window, more like pane or tile) sizing to be dynamic based on terminal resizing and based on the size of the `archive_report`, which can change dynamically during run time.

And, move a bunch of code around to be a little better structured.

2021-04-03 04:08 UTC, altendky requested changes
> And, move a bunch of code around to be a little better structured.

Definitely helpful to do that separately when it comes to others looking at the change(s).  As is the diff shows just that and it takes awhile to figure out if there are functional changes in the moved code.

Functionally I do see a difference.  Admittedly I'm running over mosh right now so...  extra whatever funny business there.  Both original and this respond to size changes.  I should probably run it locally.  You might be interested in seeing it over mosh (before and after).  I don't know what is desired so reaching conclusions when they both look a bit odd is tough.

I didn't really find any problems.  I can't say I went through it all line by line somewhat due to the mixed-purpose PR as mentioned above.  There's active development so problems will presumably get fixed if missed here.

I will note that this does shift towards being more Linux specific I think.  Not that I know how well curses works across platforms, but someone didn't mention today that they had it running in Windows.  So...  you may or may not want to make the `stty` use conditional either now or later.

2021-04-03 21:16 UTC, ericaltendorf commented on interactive.py
> +                                    start_new_session=True)
sorry about that.  more narrowly targeted changes in the future will hopefully reduce this kind of confusion.

2021-04-03 21:53 UTC, ericaltendorf commented on interactive.py
> +    last_refresh = datetime.datetime.utcfromtimestamp(0)  # Beginning of time
Thanks, fixed.

2021-04-03 21:54 UTC, ericaltendorf commented
Fixed the utcfromtimestamp(0) cruft, and made use of `stty size` conditional on a config parameter (default off, since it seems others are not experiencing the screen-resize issues I was experiencing).

2021-04-06 17:38 UTC, altendky approved these changes

2021-04-06 22:11 UTC, merged