Improve kill command
ericaltendorf/plotman pull request #801
Opened 2021-06-21 16:34 UTC by rafaelsteil

This PR adds two improvements to `plotman kill`:

1. Adds `-f` to proceed without asking for confirmation
2. Delete the files based on filesystem pattern instead of using `open_files()`, as it always left something behind.

2021-06-23 03:08 UTC, altendky requested changes
Also, needs a changelog entry.  Thanks for getting around to this, it's been a long time coming...

2021-06-23 03:08 UTC, altendky commented on src/plotman/job.py
> +                temp_files.update(glob.glob(os.path.join(dir, "plot-*-{0}.*".format(self.plot_id))))
```suggestion
                temp_files.update(glob.glob(os.path.join(dir, f"plot-*-{self.plot_id}.*")))
```

2021-06-23 03:08 UTC, altendky commented on src/plotman/plotman.py
> +        p_kill.add_argument('-f', dest='force', action='store_true', default=False, help="Don't ask for confirmation before killing the plot job")
I think...

```suggestion
        p_kill.add_argument('-f', '--force', action='store_true', default=False, help="Don't ask for confirmation before killing the plot job")
```

2021-06-23 03:08 UTC, altendky commented on src/plotman/plotman.py
> +                            print('Will delete %d temp files' % len(temp_files))
I think it would be good to output this information regardless?

2021-06-23 03:09 UTC, altendky commented
I suppose this would be both a fixed entry and an added entry.

2021-06-23 03:51 UTC, rafaelsteil commented
@altendky Ready to be reviewed again

2021-06-25 02:27 UTC, altendky requested changes
A few nitpicks but I think we're pretty much there.  If you are ok with these changes you can address them or I can finish out the busywork, no matter.

2021-06-25 02:27 UTC, altendky commented on src/plotman/plotman.py
> +                            print('Will delete %d temp files' % len(temp_files))
Don't we still want this before the confirmation?  (and also regardless of `--force`)

2021-06-25 02:27 UTC, altendky commented on src/plotman/job.py
> +                temp_files.update(glob.glob(os.path.join(dir, f"plot-*-{self.plot_id}.*")))
```suggestion
                temp_files.update(glob.glob(os.path.join(dir, f"plot-*-{self.plot_id}.tmp")))
```

2021-06-25 02:27 UTC, altendky commented on CHANGELOG.md
> +- `plotman kill` doesn't leave any temporary files behind anymore
Let's put the fixed section first like was done below in v0.4.  Also, for both entries add a link line.

```markdown
  ([#801](https://github.com/ericaltendorf/plotman/pull/801))
```

2021-06-25 02:27 UTC, altendky commented on CHANGELOG.md
> +- Added argument `-f / --force` to `plotman kill` to skip confirmation before killing the job
```suggestion
- Added argument `-f`/`--force` to `plotman kill` to skip confirmation before killing the job.
```

2021-06-25 02:49 UTC, merged